services:

  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: dacio@04

  gateway:
    image: loja/shop-gateway-api
    ports:
      - "8880:8080"
    environment:
      AUTH_API_URL: http://auth:8081
      PRODUCT_API_URL: http://product:8082
      CUSTOMER_API_URL: http://customer:8083
      SHOPPING_API_URL: http://shopping:8084
    depends_on:
      auth:
        condition: service_healthy
      product:
        condition: service_healthy
      customer:
        condition: service_healthy
      shopping:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway:8080/gateway/healthcheck" ]
      interval: 60s
      timeout: 30s
      retries: 2

  auth:
    image: loja/shop-auth-api
    ports:
      - "8881:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth:8081/auth/healthcheck" ]
      interval: 60s
      timeout: 30s
      retries: 2

  product:
    image: loja/shop-product-api
    ports:
      - "8882:8082"
    volumes:
      - ./produtos/photos:/app/photos
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://product:8082/product/healthcheck" ]
      interval: 60s
      timeout: 30s
      retries: 2

  customer:
    image: loja/shop-customer-api
    ports:
      - "8883:8083"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      PRODUCT_API_URL: http://product:8082
      AUTH_API_URL: http://auth:8081
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://customer:8083/customer/healthcheck" ]
      interval: 60s
      timeout: 30s
      retries: 2

  shopping:
    image: loja/shop-shopping-api
    ports:
      - "8884:8084"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      PRODUCT_API_URL: http://product:8082
      CUSTOMER_API_URL: http://customer:8083
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://shopping:8084/shopping/healthcheck" ]
      interval: 60s
      timeout: 30s
      retries: 2


