services:

  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: dacio@04
    healthcheck:
      test: [ "CMD", "psql", "--username=postgres",  "--command=SELECT 1 FROM pg_database WHERE datname='shop';"]

  gateway:
    image: loja/shop-gateway-api
    #build: "./gateway"
    ports:
      - "8880:8080"
    environment:
      AUTH_API_URL: http://auth:8081
      PRODUCT_API_URL: http://product:8082
      CUSTOMER_API_URL: http://customer:8083
      ORDER_API_URL: http://order:8084
    depends_on:
      auth:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway:8080/gateway/healthcheck" ]

  auth:
    image: loja/shop-auth-api
    #build: "./auth"
    ports:
      - "8881:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      CUSTOMER_API_URL: http://customer:8083
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth:8081/auth/healthcheck" ]

  product:
    image: loja/shop-product-api
    #build: "./product"
    ports:
      - "8882:8082"
    volumes:
      - ./produtos/photos:/app/photos
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://product:8082/product/healthcheck" ]

  customer:
    image: loja/shop-customer-api
    #build: "./customer"
    ports:
      - "8883:8083"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      PRODUCT_API_URL: http://product:8082
      AUTH_API_URL: http://auth:8081
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://customer:8083/customer/healthcheck" ]

  order:
    image: loja/shop-order-api
    #build: "./order"
    ports:
      - "8884:8084"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      AUTH_API_URL: http://auth:8081
      PRODUCT_API_URL: http://product:8082
      CUSTOMER_API_URL: http://customer:8083
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://order:8084/order/healthcheck" ]

