version: "3.5"
services:

  postgres:
    image: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: dacio@04

  gateway:
    image: loja/shop-gateway-api
    ports:
      - "8884:8084"
    environment:
      AUTH_API_URL: http://auth:8085
      PRODUCT_API_URL: http://product:8081
      USER_API_URL: http://user:8082
      SHOPPING_API_URL: http://shopping:8083
    depends_on:
      - postgres

  auth:
    image: loja/shop-auth-api
    ports:
      - "8885:8085"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
    depends_on:
      - postgres

  product:
    image: loja/shop-product-api
    ports:
      - "8881:8081"
    volumes:
      - ./produtos/photos:/app/photos    
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
    depends_on:
      - postgres

  user:
    image: loja/shop-user-api
    ports:
      - "8882:8082"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      PRODUCT_API_URL: http://product:8081
    depends_on:
      - postgres

  shopping:
    image: loja/shop-shopping-api
    ports:
      - "8883:8083"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      PRODUCT_API_URL: http://product:8081
      USER_API_URL: http://user:8082
    depends_on:
      - postgres
