services:

  postgres:
    image: postgres:16
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      #- ./postgres/init-collation.sh:/docker-entrypoint-initdb.d/init-collation.sh
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: dacio@04
    healthcheck:
      test: [ "CMD", "psql", "--username=postgres",  "--command=SELECT 1 FROM pg_database WHERE datname='shop';"]

  auth:
    #image: loja/shop-auth-api
    build: "./auth"
    ports:
      - "8881:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      CUSTOMER_API_URL: http://customer:8083
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth:8081/auth/health" ]

  product:
    #image: loja/shop-product-api
    build: "./product"
    ports:
      - "8882:8082"
    volumes:
      - ./produtos/photos:/app/photos
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://product:8082/product/health" ]

  customer:
    #image: loja/shop-customer-api
    build: "./customer"
    ports:
      - "8883:8083"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      PRODUCT_API_URL: http://product:8082
      AUTH_API_URL: http://auth:8081
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://customer:8083/customer/health" ]

  order:
    #image: loja/shop-order-api
    build: "./order"
    ports:
      - "8884:8084"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dacio@04
      AUTH_API_URL: http://auth:8081
      PRODUCT_API_URL: http://product:8082
      CUSTOMER_API_URL: http://customer:8083
      KAFKA_BOOTSTRAP_ADDRESS_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://order:8084/order/health" ]

  gateway:
    #image: loja/shop-gateway-api
    build: "./gateway"
    ports:
      - "8880:8080"
    environment:
      AUTH_API_URL: http://auth:8081
      PRODUCT_API_URL: http://product:8082
      CUSTOMER_API_URL: http://customer:8083
      ORDER_API_URL: http://order:8084
    depends_on:
      auth:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway:8080/gateway/health" ]

  kafka:
    image: apache/kafka:4.2.0
    #container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"